/*
 * File: z8remote/view/mainView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Z8Remote.view.mainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainView',

    config: {
        id: 'mainView',
        itemId: 'mainView',
        navigationBar: {
            id: 'mainNavi',
            itemId: 'mainNavi'
        },
        items: [
            {
                xtype: 'list',
                title: 'Z Remote',
                itemId: 'mylist',
                disableSelection: true,
                itemTpl: [
                    '<div style="font-size: 30px;">{name}</div>'
                ],
                store: 'menuData',
                itemHeight: 50,
                refreshHeightOnUpdate: false,
                variableHeights: false
            }
        ],
        listeners: [
            {
                fn: 'onMylistItemSingletap',
                event: 'itemsingletap',
                delegate: '#mylist'
            },
            {
                fn: 'onMainViewShow',
                event: 'show'
            }
        ]
    },

    onMylistItemSingletap: function(dataview, index, target, record, e, eOpts) {
        console.log('Z8: menu item tapped...');
        console.log('  ');
        console.log('  "'+record.data.name+'"');
        console.log('    ');

        if (record.data.name=='About the Zed Remote...') {
            window.open('http://www.github.com/QuinnEbert/Zedom8or','_blank');
        } else if (record.data.name=='Created by Zed Tiger...') {
            window.open('http://www.zedtiger.com/','_blank');
        }
    },

    onMainViewShow: function(component, eOpts) {
        console.log('    ');
        console.log('Z8: welcome to Z Remote! ;)');

    }

});