/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'menuItem',
        'confItem'
    ],
    stores: [
        'menuData',
        'confData'
    ],
    views: [
        'mainView',
        'initView'
    ],
    appFolder: 'z8remote',
    name: 'Z8Remote',

    getConfigValueNamed: function(named) {
        var s = Ext.getStore('confData');
        var x = 0;
        var y = s.getCount();
        var key;
        while (x < y) {
            key = s.getAt(x).get('key');
            if (key == named) return s.getAt(x).get('value');
            x = (x + 1);
        }
        return null;
    },

    delConfigValueNamed: function(named) {
        if (Z8Remote.app.getConfigValueNamed(named)!==null) {
            var s = Ext.getStore('confData');
            var x = 0;
            var y = s.getCount();
            var key;
            while (x < y) {
                key = s.getAt(x).get('key');
                if (key == named) {
                    Ext.getStore('confData').removeAt(x);
                    return;
                }
                x = (x + 1);
            }
        }
    },

    setConfigValueNamed: function(named, value) {
        Z8Remote.app.delConfigValueNamed(named);
        Ext.getStore('confData').add({key:named,value:value});
    },

    launch: function() {

        Ext.create('Z8Remote.view.initView', {fullscreen: true});
    }

});
